[project]
name = "triminomokai"
version = "0.1.0"
description = "SinglePlay AI inspired from AlphaGo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "torch>=2.7.1",
]
